### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by Ataraxiaa** [RobertoGraham/FortniteAPIJavaRestClient#1]
Doesn't resolve when I add this to my gradle project. How do I fix this? (im new to this)

**Comment by RobertoGraham** [comment]
Can you post your gradle file and any errors you have. Are you able to resolve other project jars?

**Comment by Ataraxiaa** [comment]
Is this what you are asking for?
[build.zip](https://github.com/RobertoGraham/FortniteAPIJavaRestClient/files/1933418/build.zip)

![208071f0c7e3b0c5ec7be665f85005f8](https://user-images.githubusercontent.com/38014469/39070276-bacab036-44b0-11e8-8dbb-1f6cba6488bd.png)

**Comment by RobertoGraham** [comment]
I'm a Maven user so I'm a bit stuck here too, please can you try this in terminal/command prompt inside your project folder: `gradle build --refresh-dependencies`

**Comment by Ataraxiaa** [comment]
Never mind. I'm an idiot thanks!
